version: "3.3"

services:
  db:
    container_name: postgres
    image: phdcoder/postgresbr
    restart: always
    volumes:
      - base_cliente:/var/lib/postgresql/data/pgdata
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      PGDATA: /var/lib/postgresql/data/pgdata
      LANG: pt_BR.utf8
#Em produção não deixa o banco de dados opostos

  backend:
    depends_on:
      - db
    container_name: backend
    image: imrayh/rayhbank
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - uploads:/app/uploads
    ports:
      - "81:80"

  frontend:
    container_name: frontend
    image: imrayh/front-angular
    volumes:
      - angular:/app
    ports:
      - "80:80"

volumes:
  base_cliente:
    external: true
  uploads:
    external: true
  angular:
    external: true
