version: "3.3"

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    volumes:
      - jenkins:/jenkins
    ports:
      - "9090:8080"
  db:
    container_name: postgres
    image: phdcoder/postgresbr
    restart: always
    volumes:
      - base_cliente:/var/lib/postgresql/data/pgdata
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: app
      POSTGRES_DB: easysell
      POSTGRES_PASSWORD: app2022
      PGDATA: /var/lib/postgresql/data/pgdata
      LANG: pt_BR.utf8
    ports:
      - "5455:5432"

  app:
    container_name: app
    build: .
    volumes:
      - java:/java
    ports:
      - "8082:8080"

volumes:
  base_cliente:
    external: true
  jenkins:
    external: true
  java:
    external: true